BELIEF_1 = "Peace"
BELIEF_2 = "Love"
BELIEF_3 = "Collaboration"
BELIEF_4 = "Competition"
BELIEF_5 = "Evolution"

THEORY_1 = "Energy"
THEORY_2 = "Probability"
THEORY_3 = "AI Agent"
THEORY_4 = "Entropy"
